// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewprtbvooltqyntnppvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3cHJ0YnZvb2x0cXludG5wcHZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MzY1MjUsImV4cCI6MjA2MDExMjUyNX0.VGxh0bAqa0T5UBBKh2hVPMnLq7lkRAOwE3wv7HUiiLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);